- name: "Product 1"
  url: "/product1"
  image: "/assets/images/product1.jpg"
  description: "A great product!"
  price: "29.99"
- name: "Product 2"
  url: "/product2"
  image: "/assets/images/product2.jpg"
  description: "Another cool item!"
  price: "49.99"
